// This code has been generated by AI

// Mock Chakra UI components for testing
export const Box = ({ children, ...props }: any) => (
  <div data-testid="chakra-box" {...props}>
    {children}
  </div>
);
export const Grid = ({ children, ...props }: any) => (
  <div data-testid="chakra-grid" {...props}>
    {children}
  </div>
);
export const Heading = ({ children, size, ...props }: any) => (
  <h2 data-testid="chakra-heading" {...props}>
    {children}
  </h2>
);
export const Text = ({ children, ...props }: any) => (
  <span data-testid="chakra-text" {...props}>
    {children}
  </span>
);
export const Stack = ({ children, ...props }: any) => (
  <div data-testid="chakra-stack" {...props}>
    {children}
  </div>
);
export const Container = ({ children, ...props }: any) => (
  <div data-testid="chakra-container" {...props}>
    {children}
  </div>
);
export const Spinner = ({ ...props }: any) => (
  <div data-testid="chakra-spinner" {...props}>
    Loading spinner
  </div>
);

export const Card = {
  Root: ({ children, ...props }: any) => (
    <div data-testid="chakra-card-root" {...props}>
      {children}
    </div>
  ),
  Body: ({ children, ...props }: any) => (
    <div data-testid="chakra-card-body" {...props}>
      {children}
    </div>
  ),
};

export const Badge = ({ children, ...props }: any) => (
  <span data-testid="chakra-badge" {...props}>
    {children}
  </span>
);

// Mock ChakraProvider
export const ChakraProvider = ({ children }: any) => <>{children}</>;
export const defaultSystem = {};
