name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.1.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prettier check
        run: pnpm prettier:check

      - name: Run ESLint
        run: pnpm lint

      - name: Run tests
        run: pnpm test -- --coverage --watchAll=false

      - name: Build
        run: pnpm build